### PR TITLE
Add CSV export for IHCC view

### LINKED ISSUE #23: Export GECKO IHCC as CSV
Hi - would it please be possible to add a CSV export to the makefile? Contributors like handling the model in a spreadsheet, so the ability to load an up to date version in sync with the OWL would be very useful to make sure they are using the right version of the model (instead of the original CINECA WP3 spreadsheet)

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #23 

Currently ordered by ID, but please let me know if you'd like it to be ordered a different way (e.g., label or parent).

Lines 115-120 are a bit weird because the PDRO definition for that term contains line breaks... not sure if we want to do something about this. It displays OK in Excel.

### CODE REVIEW

**Comment by jamesaoverton** [comment]
@mcourtot You can preview the table here: https://github.com/IHCC-cohorts/GECKO/blob/2d13448f5c5e72854d978f4dd0bc0696654d0a27/views/ihcc-gecko.csv

**Comment by jamesaoverton** [comment]
@mcourtot Does this table look good to you? https://github.com/IHCC-cohorts/GECKO/blob/2d13448f5c5e72854d978f4dd0bc0696654d0a27/views/ihcc-gecko.csv

**Comment by mcourtot** [comment]
I'm going to ask for my ideal outcome in case it's easy to tweak, if it is too much work the table above is ok

1. Can we have the columns order be, from the left: Category (ie subclass of), ID, label, definition (suspect trivial)
2. Can we have the categories in order/depth. For example consider the hierarchy 
           physio measurement > anthropometry > height
Can we have left most column be physio measurement, then next one be anthropometry then next be all subclasses height etc?
To emulate the structure of https://docs.google.com/spreadsheets/d/1ZXqTMIhFtGOaodw7Fns5YghvY_pWos-RuSa2BFnO5l4/edit#gid=0 with broad category, sub-category etc  (suspect hard, but maybe having all the IHCC facets be broad category could be a good intermediate solution (ie we would have 'physio measurement' as broad category, then anthropometry and height in same column)

**Comment by beckyjackson** [comment]
I just pushed some changes. @mcourtot could you please check out this table and let me know if this is what you're thinking?
https://github.com/IHCC-cohorts/GECKO/blob/8b2e43bd6e9f90e5f30ba9098c2f232c4f17a59d/views/ihcc-gecko.csv

Also, I can always remove the "definition" column if you think it doesn't really help.

**Comment by jamesaoverton** [comment]
@mcourtot We're just waiting for your feedback on this PR.

**Review by mcourtot — APPROVED** [review]
+1

**Pull request merged**
