### PR TITLE
Add six cognitive measurements and two diseases

### PR DESCRIPTION
**Pull request by beckyjackson**
Six new cognitive measurement tests in support of the DAC work:
* Montreal Cognitive Assessment Test (MoCA)
* CERAD Neuropsychological Battery
* Penn Computerized Neurocognitive  Battery (Penn CNB)
* Severe Impairment Battery (SIB)
* Neuropsychiatric Inventory (NPI)
* Clinical Dementia Rating Scale (CDRS)

I also changed the other test labels from ending with "measurement" to ending with "score", since a score is really the output from the tests. I can revert this change if we prefer "measurement".

I also added two new disease categories:
* congenital disorder (new GECKO term)
* reproductive system disease (term from MONDO)

MONDO has "disorder of development or morphogenesis", but I don't think this is quite right because this is talking about *structural* issues whereas we want to cover *all* congenital/genetic disorders.

I want the browser label for this to be "congenital and genetic disorders" to be more clear that both of those are covered here, so it's more of a grouping term.

Finally, I removed "connective tissue disease" because we already have "musculoskeletal system disease" and thus far we can cover everything with that instead. I can add this back in if we prefer to keep it.

### CODE REVIEW

**Review by jamesaoverton — APPROVED** [review]

**Review by jamesaoverton — APPROVED** [review]
I guess you don't need 'connective tissue disease' anymore? Otherwise looks good.

**Comment by beckyjackson** [comment]
@mcourtot have you had a chance to review these changes? Thanks!

**Comment by mcourtot** [comment]
I didn't realise you were waiting for me, sorry. They look reasonable to me, tbh you probably know better anyway :)

**Comment by beckyjackson** [comment]
Thanks much!

**Pull request merged**
