### PR TITLE
Update IHCC labels for lifestyle history terms

### LINKED ISSUE #26: lifestyle classes label
https://registry.ihccglobal.app/ontologies/gecko/terms?iri=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FGECKO_0000067&viewMode=All&siblings=true

Should subclasses of lifestyle be called "xxx history" eg 'drug history'? It seems a little bit confusing to be just labeled 'drugs'

### PR DESCRIPTION
**Pull request by beckyjackson**
Resolves #26

* drugs -> recreational drug history
* alcohol -> alcohol use history
* tobacco -> tobacco use history
* nutrition -> dietary history
* sleep -> sleep history
* oral health and hygiene -> oral health history
* physical activity -> physical activity history

### CODE REVIEW

**Review by jamesaoverton — APPROVED** [review]

**Comment by beckyjackson** [comment]
@mcourtot could you take a quick look and let me know if these changes were what you expected?

Thanks!

**Comment by mcourtot** [comment]
question around oral health and hygiene becoming oral health history.
is it oral (health and hygiene) or is it (oral health) and hygiene (where hygiene could be "how many showers do you take a week" for example) If the former seems good, if the latter we may miss on the hygiene bit with the new mapping?

**Comment by beckyjackson** [comment]
Good question! I guess I was thinking that things like brushing your teeth and flossing were part of oral health, but I could see that being confusing. Should I change that to "oral health and hygiene history"?

**Comment by mcourtot** [comment]
Apologies if I was unclear. In the original, does hygiene mean only "oral hygiene" or does it mean hygiene in general? While flossing and brushing teeth are part of oral hygiene, taking a shower would not for example.

**Comment by beckyjackson** [comment]
No worries. It's only relating to oral hygiene, not other hygiene.

**Comment by mcourtot** [comment]
thanks! looks great to me.

**Pull request merged**
