### PR TITLE
Extend GECKO with Maelstrom terms

### PR DESCRIPTION
**Pull request by beckyjackson**
See full set of new term additions in #11 

The four NTRs for EUPATH have temporary IDs that shouldn't be merged. Depending on if EUPATH wants these terms (https://github.com/VEuPathDB-ontology/VEuPathDB-ontology/issues/84), we will update to the EUPATH ID or assign a new GECKO ID.

Note that I've also moved all external terms to the `external` sheet, since we have quite a few now.

### CODE REVIEW

**Comment by beckyjackson** [comment]
This is more or less ready, but there are a couple terms that use temporary EUPATH IDs (like `GECKO:EUPATH_1`) while we wait to see if EUPATH wants to add them or not. Do we want to just give these GECKO IDs for now?

Alternatively, we could just remove them for now.

**Comment by beckyjackson** [comment]
Looks like those EUPATH terms are being redirected to ENVO - EnvironmentOntology/envo#1008

**Comment by mcourtot** [comment]
Hi @beckyjackson : thinking about writing a paper about this in short term. Is there a way to keep track of this kind of detailed work (enriching/coordinating with other resources) as it'd be good to report on it. There is probably other pieces to think about, so a list somewhere could really help to remember.

**Comment by beckyjackson** [comment]
@mcourtot I can absolutely make a Google Spreadsheet with all the terms we've added and where they came from, or similar terms. Would that be useful?

**Comment by beckyjackson** [comment]
I've removed those temporary EUPATH terms from this PR. We can add them as soon as they are added to EUPATH/ENVO in a separate PR. This is ready to go.

**Pull request merged**
